baseURL = "https://dougscafe.netlify.app/"
languageCode = "en-us"
theme = "anatole"
summarylength = 30
enableEmoji = true
enableRobotsTXT = true
# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"


[params]
title = "Dougs' Café"
author = "Douglas Barbosa"
description = "Olá, Seja bem vindo ao meu blog."
profilePicture = "images/profile.png"
displayMode = "dark"
#googleSiteVerify = ""
#googleAnalytics = ""
keywords = "blog"
favicon = "favicons/"
mainSections = ["posts"]
# Google Site Verification
#googleSiteVerify = "valid google"
images = ["images/profile.png"]

## Social links
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/mako_reactor"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:douglas.santosb@gmail.com"


## menu links

[menu]
[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/posts/"

[[menu.main]]
name = "Sobre"
weight = 300
identifier = "about"
url = "/about/"

[[menu.main]]
name = "Tags"
weight = 400
identifier = "tags"
url = "/tags/"

[[menu.main]]
name = "Categorias"
weight = 500
identifier = "categories"
url = "/categories/"




